// worksList: 작업물 리스트
const worksSettingList = [
  {
    name: "shinhan1",
    link: "/work/shinhan",
    image: "PC_Card_project03.png",
    projectName: "신한 슈퍼 SQL 유지운영 2024",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient: "#0046FF",
    use: true,
    detail: {
      coverPc: "/works/shinhan/cover.png",
      coverMobile: "/works/shinhan/cover_m.png",
      title: "신한 슈퍼SOL 유지 <span class='br_pc'></span>운영 2024",
      subtitle:
        "신한금융그룹의 새로운 여정,<span class='br_pc'></span>신한 슈퍼 SoL",
      overview:
        "신한금융그룹의 모든 금융 네트워크를 한 곳에서 해결할 수 있는 신한 슈퍼 SoL이 출시되면서 신한플러스에서 제공하던 서비스가 신한 슈퍼 SoL로 이전되었습니다. 인스플래닛은 신한플러스 서비스에서 안정적인 유지운영을 진행해 왔으며, 서비스 이관 후 2024년에도 유지운영 업무를 수행하고 있습니다.",
      launch: "Jan, 2024",
      client: "신한금융그룹",
      device: "Mobile Application",
      uiux: "Prototyping, Wireframing, UI Design, Maintenance",
      viewplatform: "https://www.shinhan.com/index.jsp",
    },
  },
  {
    name: "shinhan1",
    link: "", // link 가 null 이거나 "" 일 경우 메인 화면에 노출되지 않습니다.
    image: "PC_Card_project03.png",
    projectName: "신한 슈퍼 SQL 유지운영 2024",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient: "#0046FF",
    use: true, // use 가 false 일 경우 메인 화면, work 에 노출되지 않습니다.
    detail: {
      coverPc: "/works/shinhan/cover.png",
      coverMobile: "/works/shinhan/cover_m.png",
      title: "신한 슈퍼SOL 유지 <span class='br_pc'></span>운영 2024",
      subtitle:
        "신한금융그룹의 새로운 여정,<span class='br_pc'></span>신한 슈퍼 SoL",
      overview:
        "신한금융그룹의 모든 금융 네트워크를 한 곳에서 해결할 수 있는 신한 슈퍼 SoL이 출시되면서 신한플러스에서 제공하던 서비스가 신한 슈퍼 SoL로 이전되었습니다. 인스플래닛은 신한플러스 서비스에서 안정적인 유지운영을 진행해 왔으며, 서비스 이관 후 2024년에도 유지운영 업무를 수행하고 있습니다.",
      launch: "Jan, 2024",
      client: "신한금융그룹",
      device: "Mobile Application",
      uiux: "Prototyping, Wireframing, UI Design, Maintenance",
      viewplatform: "https://www.shinhan.com/index.jsp",
    },
  },
  {
    name: "lgcns_cloudxper",
    link: "/work/lgCloudXper",
    image: "card_lg_cloud_xper.png",
    projectName: "LG Cloud Xper",
    projectClient: "LG CNS",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient:
      "linear-gradient(114deg, #E5437A 33.15%, #F28D52 75.83%, #FFD028 105.1%)",
    use: true,
    detail: {
      coverPc: "/works/lgcns_cloudxper/cover.png",
      coverMobile: "/works/lgcns_cloudxper/cover_m.png",
      title: "LG Cloud Xper",
      subtitle:
        "모든 클라우드 서비스를 <span class='br_pc'></span>‘엔드 투 엔드(end-to-end)’로 <span class='br_pc'></span>제공하는 <span class='br_pc'></span>LG CNS 클라우드 브랜드<span class='br_pc'></span>LG Cloud Xper ",
      overview:
        "2023년, 인스플래닛은 LG CNS 의 클라우드 플랫폼 및 운영관리 솔루션 UI 개선을 진행했다. IT 전문기업으로 클라우드 비즈니스에 대한 높은 이해도와 수많은 경험을 가진 LG CNS 와 프로젝트 1차 개선을 완료한 상태이며 인스플래닛은 전반적인 UIUX디자인 개선 및 리액트를 활용한 퍼블리싱을 주도적으로 작업했다. LG Cloud Xper 는 클라우드 진단과 컨설팅부터 전환, 운영까지 모든 클라우드 서비스를 ‘엔드 투 엔드(end-to-end)’로 제공하는 LG CNS 클라우드 브랜드 이다.",
      launch: "Oct,2023",
      client: "LG CNS",
      device: "PC",
      uiux: "UX Concept Building, UI Concept Building, Lo-fi Prototyping, Wireframing, UI Design, Figma, Material UI, React UI ",
      viewplatform: "#none",
    },
  },
  {
    name: "homeAndShopping",
    link: "/work/homeAndShopping",
    image: "card_homeAndShopping.png",
    projectName: "신한 슈퍼 SQL 유지운영 2024",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient: "rgb(234, 191, 225)",
    use: true,
    detail: {
      coverPc: "/works/homeAndShopping/cover.png",
      coverMobile: "/works/homeAndShopping/cover_m.png",
      title: "홈앤쇼핑 카카오 <span class='br_pc'></span>챗봇 서비스 구축",
      subtitle:
        "내 손안의 도우미,<span class='br_pc'></span> 홈앤쇼핑 챗봇 서비스 도입",
      overview:
        "카카오톡 챗봇 템플릿의 UI 디자인과 퍼블리싱을 진행하였습니다. Claymorphism 아이콘을 활용하여 홈앤쇼핑의 트렌디한 이미지를 구현하였습니다.",
      launch: "Jun, 2023",
      client: "홈앤쇼핑",
      device: "Mobile Application",
      uiux: "User Analysis, Benchmarking, UX Concept Building, UI Concept Building, UI Design, Figma",
      viewplatform: "#none",
    },
  },
  {
    name: "paEnter",
    link: "/work/paEnter",
    image: "card_pa_enter.png",
    projectName: "PA엔터테인먼트 오피셜 사이트 구축",
    projectClient: "PA엔터테인먼트",
    projectType: "-",
    projectYear: "2023",
    gradient: "#402743",
    use: true,
    detail: {
      coverPc: "/works/paEnter/cover.png",
      coverMobile: "/works/paEnter/cover_m.png",
      title: "PA엔터테인먼트<span class='br_pc'></span> 오피셜 사이트 구축",
      subtitle: "한류와 대중문화의 중심을<span class='br_pc'></span> 주도하다.",
      overview:
        "급변하고 있는 문화 트렌드와 한류의 방향성을 파악하여 오랜 기간 활동을 이어온 뮤지션과 배우를 중심으로 대중문화의 발전에 기여하고, 글로벌 시장에서 종합 문화예술 엔터테인먼트 회사로 도약하고자하는 PA엔터테인먼트의 포부를 담아 PA엔터테인먼트의 브랜드 컬러와 새로운 UI/UX 전략을 수립하였습니다.",
      launch: "Apr, 2023",
      client: "PA엔터테인먼트",
      device: "Web(PC/Mobile)",
      uiux: "Benchmarking, UX Concept Building, UI Concept Building,Menu Architecture, Prototyping, Wireframing, UI Design, Figma, Test Scenario, Wix",
      viewplatform: "#none",
    },
  },
  {
    name: "t4k",
    link: "/work/t4k",
    image: "card_t4k.png",
    projectName: "T4K 브랜드 사이트 구축",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient:
      "linear-gradient(120deg, rgba(170,185,195,1) 0%, rgba(119,119,119,1) 100%)",
    use: true,
    detail: {
      coverPc: "/works/t4k/cover.png",
      coverMobile: "/works/t4k/cover_m.png",
      title: "T4K 브랜드<span class='br_pc'></span>사이트 구축",
      subtitle:
        "More than OK - 화물차<span class='br_pc'></span>운전자에게 최적화된 기능만 쏙쏙 뽑아 담은 전기트럭",
      overview:
        "GS글로벌에서 판매하는 BYD 1톤 전기트럭 T4K의 공식 웹사이트이며, 신규 출시된 T4K의 일관된 톤앤매너와 차별화된 제품 USP로 브랜드 아이덴티티를 확립하고 다양한 형태의 정보를 안정적으로 제공하기 위해 확장성이 고려된 유연한 UX 설계를 구현하였습니다.",
      launch: "Apr, 2023",
      client: "GS글로벌",
      device: "Web(PC/Mobile)",
      uiux: "Benchmarking, UX Concept Building, UI Concept Building, Menu Architecture, Prototyping, Wireframing, UI Design, Figma, Test Scenario, CMS",
      viewplatform: "#none",
    },
  },
  {
    name: "cosmo",
    link: "/work/cosmo",
    image: "card_cosmo.png",
    projectName: "1회용컵 보증금 관리시스템 고도화",
    projectClient: "자원순환보증금관리센터",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient:
      "linear-gradient(120deg, rgba(170,185,195,1) 0%, rgba(119,119,119,1) 100%)",
    use: true,
    detail: {
      coverPc: "/works/cosmo/cover.png",
      coverMobile: "/works/cosmo/cover_m.png",
      title: "1회용컵 보증금<span class='br_pc'></span> 관리시스템 고도화",
      subtitle:
        "지구를 구하는 더하기가 아닌 빼기<span class='br_pc'></span> 1회용 컵 보증금 제도",
      overview:
        "1회용컵 보증금 제도 시행에 따라 자원순환보증금관리센터-사업자-회수사업자-소비자 간 4개의 플랫폼에 제공하고 있는 서비스의 기능 고도화와 인스플래닛의 UI/UX 전략에 의해 수립된 가이드에 따른 디자인 고도화를 진행하였습니다.",
      launch: "Dec, 2022",
      client: "자원순환보증금관리센터",
      device: "Web(PC/Mobile)",
      uiux: "User Analysis, Benchmarking, UX Concept Building, UI Concept Building, User Flow, Menu Architecture, Prototyping, Wireframing, UI Design, Figma, Test Scenario",
      viewplatform: "#none",
    },
  },
  {
    name: "pims",
    link: "/work/pims",
    image: "card_pims.png",
    projectName: "KB 개인정보관리 시스템(PIMS) UI/UX",
    projectClient: "KB국민은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient: "#f6be41",
    use: true,
    detail: {
      coverPc: "/works/pims/cover.png",
      coverMobile: "/works/pims/cover_m.png",
      title:
        "KB 개인정보관리<span class='br_pc'></span> 시스템(PIMS)<span class='br_pc'></span> UI/UX",
      subtitle: "업무 전산화에 따른 UI/UX 전략<span class='br_pc'></span> 수립",
      overview:
        "1회용컵 보증금 제도 시행에 따라 자원순환보증금관리센터-사업자-회수사업자-소비자 간 4개의 플랫폼에 제공하고 있는 서비스의 기능 고도화와 인스플래닛의 UI/UX 전략에 의해 수립된 가이드에 따른 디자인 고도화를 진행하였습니다.",
      launch: "Nov, 2022",
      client: "KB국민은행",
      device: "PC Web",
      uiux: "Benchmarking, UX Concept Building, UI Concept Building, Prototyping, Wireframing, UI Design, Figma",
      viewplatform: "#none",
    },
  },
  {
    name: "heyoung",
    link: "/work/heyoung",
    image: "card_heyoung.png",
    projectName: "헤이영 캠퍼스 고도화",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2022",
    gradient:
      "linear-gradient(214deg, #6B71EE -12.26%, #6D72EE 35.23%, #E586E3 91.39%, #D786E3 144.03%)",
    use: true,
    detail: {
      coverPc: "/works/heyoung/cover.png",
      coverMobile: "/works/heyoung/cover_m.png",
      title: "헤이영 캠퍼스<span class='br_pc'></span> 고도화",
      subtitle: "스마트한 대학생활 필수 통합앱",
      overview:
        "다크테마를 포함한 컬러 테마와 모바일 학생증 커스텀 기능을 제공하여 디자인 구성요소의 고도화 및 차별화를 구현하고 게시판, 소모임 등의 프로세스 개선으로 서비스를 업그레이드 하였습니다.",
      launch: "Oct, 2022",
      client: "신한은행",
      device: "Mobile Application",
      uiux: "Benchmarking, UX Concept Building, UI Concept Building, User Flow, Menu Architecture, Prototyping, Wireframing, UI Design, Figma, Test Scenario",
      viewplatform: "#none",
    },
  },
  {
    name: "shinhanPlus",
    link: "/work/shinhanPlus",
    image: "card_shinhanPlus.png",
    projectName: "신한플러스 해외주식 소수점투자 UI/UX",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2022",
    gradient: "#fff",
    use: true,
    detail: {
      coverPc: "/works/shinhanPlus/cover.png",
      coverMobile: "/works/shinhanPlus/cover_m.png",
      title:
        "신한플러스<span class='br_pc'></span> 해외주식<span class='br_pc'></span> 소수점투자 UI/UX",
      subtitle: "해외주식 소수점 투자",
      overview:
        "신한금융그룹의 서비스를 한 눈에 확인하고 이용할 수 있는 신한플러스 서비스에 국내 최초로 신한투자증권이 해외주식 소수점투자 서비스를 제공하게 되었습니다. 신한플러스의 가이드를 준수하였으며, 생소한 소수점 주식 거래와 다양한 형태의 투자 방식에 대해 이용의 용이성을 높이고, 거래의 편의성을 중심으로 UI/UX를 구현하였습니다.",
      launch: "Aug, 2022",
      client: "신한은행",
      device: "Mobile Application",
      uiux: "Benchmarking, User Flow, Menu Architecture, Prototyping, Wireframing, UI Design, Figma, Test Scenario",
      viewplatform: "#none",
    },
  },
  {
    name: "lgObjet",
    link: "/work/lgObjet",
    image: "card_lgObjet.png",
    projectName: "LG전자 제품 USP디자인",
    projectClient: "LG 전자",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2022",
    gradient:
      "linear-gradient(120deg, rgba(235,197,196,1) 0%, rgba(191,160,142,1) 100%)",
    use: true,
    detail: {
      coverPc: "/works/lgObjet/cover.png",
      coverMobile: "/works/lgObjet/cover_m.png",
      title: "LG전자<span class='br_pc'></span> 제품 USP디자인",
      subtitle: "일상에 스며든 LG 오브제 컬렉션",
      overview:
        "LG전자 오브제 컬렉션의 다양한 색상과 재질을 강조하기 위한 USP 디자인과 전자제품에 따른 인테리어 및 내부 연출 컷 디자인 프로젝트를 진행하였습니다.",
      launch: "Aug, 2022",
      client: "LG 전자",
      device: "PC Web / Mobile Web",
      uiux: "UI Concept Building, Prototyping, Wireframing, UI Design, Figma",
      viewplatform: "#none",
    },
  },
  {
    name: "kbMyData",
    link: "/work/kbMyData",
    image: "card_kbMyData.png",
    projectName: "KB금융그룹 마이데이터 포털",
    projectClient: "LG 전자",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2022",
    gradient:
      "linear-gradient(153deg, rgba(55,167,183,1) 0%, rgba(3,7,12,1) 100%)",
    use: true,
    detail: {
      coverPc: "/works/kbMyData/cover.png",
      coverMobile: "/works/kbMyData/cover_m.png",
      title: "KB금융그룹<span class='br_pc'></span> 마이데이터 포털",
      subtitle: "여기저기 흩어져 있는 내 정보를 한 곳에서~",
      overview:
        "분산된 나의 데이터를 한 곳에서 모아보는 마이데이터 시대의 개막에 맞추어 축적된 데이터의 분석과 효율적인 관리로 즉각적인 인사이트를 확보하기 위한 맞춤형 분석 플랫폼을 구축하였습니다.",
      launch: "Mar, 2023",
      client: "KB금융그룹",
      device: "PC Web",
      uiux: "Benchmarking, UX Concept Building, UI Concept Building, Prototyping, Wireframing, UI Design, Figma",
      viewplatform: "#none",
    },
  },
  {
    name: "kmc",
    link: "/work/kmc",
    image: "card_kmc.png",
    projectName: "열차제어시스템 암호키관리센터(KMC) UI",
    projectClient: "LG 전자",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2022",
    gradient: "linear-gradient(65deg, #034AA9 17.9%, #3B7AFC 84.38%)",
    use: true,
    detail: {
      coverPc: "/works/kmc/cover.png",
      coverMobile: "/works/kmc/cover_m.png",
      title: "열차제어시스템<span class='br_pc'></span> 암호키관리센터(KMC) UI",
      subtitle: "열차제어시스템 암호키관리센터",
      overview:
        "지·차상 간 무선전송 데이터의 보안을 위한 암호키 관리장치인 키관리센터(KMC) 시스템의 On/Off-line 통합 인터페이스와 운영자 편의를 고려한 UX 가이드를 수립하였습니다.",
      launch: "2022.01~2022.02",
      client: "남부솔루션",
      device: "Web(PC)",
      uiux: "Benchmarking, UX Concept Building, UI Concept Building, Menu Architecture, Prototyping, Wireframing, UI Design, Test Scenario",
      viewplatform: "#none",
    },
  },
  {
    name: "iros",
    link: "/work/iros",
    image: "card_iros.png",
    projectName: "인터넷 등기소 차세대 시스템 UI/UX 전략수립",
    projectClient: "LG 전자",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2022",
    gradient: "#d9dfeb",
    use: true,
    detail: {
      coverPc: "/works/iros/cover.png",
      coverMobile: "/works/iros/cover_m.png",
      title:
        "인터넷 등기소<span class='br_pc'></span> 차세대 시스템<span class='br_pc'></span> UI/UX 전략수립",
      subtitle: "-",
      overview:
        "대법원의 인터넷 등기 시스템의 대민 채널인 인터넷 등기소의 차세대 UI/UX의 전략을 수립하고, 전략에 따른 화면 구현정책 및 UI/UX의 표준화 프로젝트를 진행하였습니다.",
      launch: "2025년 런칭 예정",
      client: "대법원",
      device: "PC Web / Mobile Web",
      uiux: "Benchmarking, UX Concept Building, UI Concept Building, User Flow, Menu Architecture, Prototyping, Wireframing, UI Design, Figma, Test Scenario",
      viewplatform: "#none",
    },
  },
  {
    name: "penthill",
    link: "/work/penthill",
    image: "card_penthill.png",
    projectName: "마이홈즈 어플리케이션 구축",
    projectClient: "블루컴",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2021",
    gradient:
      "linear-gradient(172deg, rgba(78,72,115,1) 0%, rgba(171,143,172,1) 32%, rgba(224,205,199,1) 100%)",
    use: true,
    detail: {
      coverPc: "/works/penthill/cover.png",
      coverMobile: "/works/penthill/cover_m.png",
      title: "마이홈즈<span class='br_pc'></span> 어플리케이션 구축",
      subtitle: "하이엔드 라이프 서비스 플랫폼",
      overview:
        "팬데믹에 따른 비대면 서비스 증가로 아파트 관리 앱의 사용률이 증가하였습니다. 관리사무소의 역할 및 청구서 제공, 관리비 지급 처리 등의 금융 연계서비스를 제공하고 생활편의를 위한 다양한 서비스와 소통을 위한 커뮤니티 기능 등 단순 관리 앱에서 서비스 플랫폼으로의 확대에 최적화된 UIUX를 제안하고 구축하였습니다.",
      launch: "Sep, 2021",
      client: "블루컴",
      device: "Mobile Application",
      uiux: "Benchmarking, UX Concept Building, UI Concept Building, User Flow, Menu Architecture, Prototyping, Wireframing, UI Design, Test Scenario",
      viewplatform: "#none",
    },
  },
  {
    name: "bizpay",
    link: "/work/bizpay",
    image: "card_bizpay.png",
    projectName: "유니코어 비즈페이 어플리케이션 구축",
    projectClient: "비즈페이",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2021",
    gradient:
      "linear-gradient(180deg, rgba(84,138,72,1) 0%, rgba(27,98,91,1) 100%)",
    use: true,
    detail: {
      coverPc: "/works/bizpay/cover.png",
      coverMobile: "/works/bizpay/cover_m.png",
      title: "유니코어 비즈페이<span class='br_pc'></span> 어플리케이션 구축",
      subtitle: "Portal Payment solution",
      overview:
        "비즈페이는 앱 가입 만으로 현금영수증, 카드결제, 수기결제가 가능한 간편결제 솔루션입니다. 임팩트 있는 폰트와 사이즈로 더 빠르게 서비스를 이용할 수 있고 읽기 쉬운 앱을 만들었습니다.",
      launch: "Jul, 2021",
      client: "비즈페이",
      device: "Mobile Application",
      uiux: "Benchmarking, UX Concept Building, UI Concept Building, User Flow, Menu Architecture, Prototyping, Wireframing, UI Design, Test Scenario",
      viewplatform: "#none",
    },
  },
  {
    name: "cosmo2",
    link: "/work/cosmo2",
    image: "card_cosmo2.png",
    projectName: "1회용컵 보증금 관리시스템 구축",
    projectClient: "자원순환보증금관리센터",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2022",
    gradient:
      "linear-gradient(301deg, rgba(41,117,155,1) 0%, rgba(14,61,151,1) 100%)",
    use: true,
    detail: {
      coverPc: "/works/cosmo2/cover.png",
      coverMobile: "/works/cosmo2/cover_m.png",
      title: "1회용컵 보증금<span class='br_pc'></span> 관리시스템 구축",
      subtitle: "지구를 구하는 더하기가 아닌 빼기 1회용 컵 보증금 제도",
      overview:
        "1회용컵 보증금 제도 시행에 따라 보증금 부과, 반환 및 회수, 재활용 등 전 과정을 모니터링 할 수 있는 관리체계의 프로세스와 UI/UX 구현전략을 수립하고, 자원순환보증금관리 센터-사업자-회수사업자-소비자 간 4개의 플랫폼을 아우르는 UI/UX를 전담하였습니다.",
      launch: "Dec, 2022",
      client: "자원순환보증금관리센터",
      device: "Web(PC/Mobile)",
      uiux: "User Analysis, Benchmarking, UX Concept Building, UI Concept Building, User Flow, Menu Architecture, Prototyping, Wireframing, UI Design, Figma, Test Scenario",
      viewplatform: "#none",
    },
  },

  {
    name: "kb5",
    link: "/work/kb",
    image: "PC_Card_project26.png",
    projectName: "신한 슈퍼 SQL 유지운영 2024",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient:
      "linear-gradient(45deg, hsl(240deg 100% 20%) 0%, hsl(289deg 100% 21%) 11%, hsl(315deg 100% 27%) 22%, hsl(329deg 100% 36%) 33%, hsl(337deg 100% 43%) 44%, hsl(357deg 91% 59%) 56%, hsl(17deg 100% 59%) 67%, hsl(34deg 100% 53%) 78%, hsl(45deg 100% 50%) 89%, hsl(55deg 100% 50%) 100%)",
    use: true,
  },
  {
    name: "hug6",
    link: "/work/hug",
    image: "PC_Card_project46.png",
    projectName: "신한 슈퍼 SQL 유지운영 2024",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient:
      "linear-gradient(45deg, hsl(240deg 100% 20%) 0%, hsl(289deg 100% 21%) 11%, hsl(315deg 100% 27%) 22%, hsl(329deg 100% 36%) 33%, hsl(337deg 100% 43%) 44%, hsl(357deg 91% 59%) 56%, hsl(17deg 100% 59%) 67%, hsl(34deg 100% 53%) 78%, hsl(45deg 100% 50%) 89%, hsl(55deg 100% 50%) 100%)",
    use: true,
  },
  {
    name: "temp7",
    link: "/work/temp",
    image: "PC_Card_project57.png",
    projectName: "신한 슈퍼 SQL 유지운영 2024",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient:
      "linear-gradient(45deg, hsl(240deg 100% 20%) 0%, hsl(289deg 100% 21%) 11%, hsl(315deg 100% 27%) 22%, hsl(329deg 100% 36%) 33%, hsl(337deg 100% 43%) 44%, hsl(357deg 91% 59%) 56%, hsl(17deg 100% 59%) 67%, hsl(34deg 100% 53%) 78%, hsl(45deg 100% 50%) 89%, hsl(55deg 100% 50%) 100%)",
    use: false,
  },
  {
    name: "project-about8",
    link: "",
    image: "Card.png",
    projectName: "신한 슈퍼 SQL 유지운영 2024",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient:
      "linear-gradient(45deg, hsl(240deg 100% 20%) 0%, hsl(289deg 100% 21%) 11%, hsl(315deg 100% 27%) 22%, hsl(329deg 100% 36%) 33%, hsl(337deg 100% 43%) 44%, hsl(357deg 91% 59%) 56%, hsl(17deg 100% 59%) 67%, hsl(34deg 100% 53%) 78%, hsl(45deg 100% 50%) 89%, hsl(55deg 100% 50%) 100%)",
    use: true,
  },
  {
    name: "shinhan9",
    link: "/work/shinhan",
    image: "PC_Card_project03.png",
    projectName: "신한 슈퍼 SQL 유지운영 2024",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient:
      "linear-gradient(45deg, hsl(240deg 100% 20%) 0%, hsl(289deg 100% 21%) 11%, hsl(315deg 100% 27%) 22%, hsl(329deg 100% 36%) 33%, hsl(337deg 100% 43%) 44%, hsl(357deg 91% 59%) 56%, hsl(17deg 100% 59%) 67%, hsl(34deg 100% 53%) 78%, hsl(45deg 100% 50%) 89%, hsl(55deg 100% 50%) 100%)",
    use: true,
  },
  {
    name: "lgcns10",
    link: "/work/lgcns",
    image: "PC_Card_project06.png",
    projectName: "신한 슈퍼 SQL 유지운영 2024",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient:
      "linear-gradient(45deg, hsl(240deg 100% 20%) 0%, hsl(289deg 100% 21%) 11%, hsl(315deg 100% 27%) 22%, hsl(329deg 100% 36%) 33%, hsl(337deg 100% 43%) 44%, hsl(357deg 91% 59%) 56%, hsl(17deg 100% 59%) 67%, hsl(34deg 100% 53%) 78%, hsl(45deg 100% 50%) 89%, hsl(55deg 100% 50%) 100%)",
    use: true,
  },
  {
    name: "project-about",
    link: "/work/project-about",
    image: "Card.png",
    projectName: "신한 슈퍼 SQL 유지운영 2024",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient:
      "linear-gradient(45deg, hsl(240deg 100% 20%) 0%, hsl(289deg 100% 21%) 11%, hsl(315deg 100% 27%) 22%, hsl(329deg 100% 36%) 33%, hsl(337deg 100% 43%) 44%, hsl(357deg 91% 59%) 56%, hsl(17deg 100% 59%) 67%, hsl(34deg 100% 53%) 78%, hsl(45deg 100% 50%) 89%, hsl(55deg 100% 50%) 100%)",
    use: true,
  },
  {
    name: "t4k",
    link: "https://gsgev.com/",
    image: "t4k.png",
    projectName: "신한 슈퍼 SQL 유지운영 2024",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient:
      "linear-gradient(45deg, hsl(240deg 100% 20%) 0%, hsl(289deg 100% 21%) 11%, hsl(315deg 100% 27%) 22%, hsl(329deg 100% 36%) 33%, hsl(337deg 100% 43%) 44%, hsl(357deg 91% 59%) 56%, hsl(17deg 100% 59%) 67%, hsl(34deg 100% 53%) 78%, hsl(45deg 100% 50%) 89%, hsl(55deg 100% 50%) 100%)",
    use: true,
  },
  {
    name: "kb",
    link: "/work/kb",
    image: "PC_Card_project26.png",
    projectName: "신한 슈퍼 SQL 유지운영 2024",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient:
      "linear-gradient(45deg, hsl(240deg 100% 20%) 0%, hsl(289deg 100% 21%) 11%, hsl(315deg 100% 27%) 22%, hsl(329deg 100% 36%) 33%, hsl(337deg 100% 43%) 44%, hsl(357deg 91% 59%) 56%, hsl(17deg 100% 59%) 67%, hsl(34deg 100% 53%) 78%, hsl(45deg 100% 50%) 89%, hsl(55deg 100% 50%) 100%)",
    use: true,
  },
  {
    name: "hug",
    link: "/work/hug",
    image: "PC_Card_project46.png",
    projectName: "신한 슈퍼 SQL 유지운영 2024",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient:
      "linear-gradient(45deg, hsl(240deg 100% 20%) 0%, hsl(289deg 100% 21%) 11%, hsl(315deg 100% 27%) 22%, hsl(329deg 100% 36%) 33%, hsl(337deg 100% 43%) 44%, hsl(357deg 91% 59%) 56%, hsl(17deg 100% 59%) 67%, hsl(34deg 100% 53%) 78%, hsl(45deg 100% 50%) 89%, hsl(55deg 100% 50%) 100%)",
    use: true,
  },
  {
    name: "temp",
    link: "/work/temp",
    image: "PC_Card_project57.png",
    projectName: "신한 슈퍼 SQL 유지운영 2024",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient:
      "linear-gradient(45deg, hsl(240deg 100% 20%) 0%, hsl(289deg 100% 21%) 11%, hsl(315deg 100% 27%) 22%, hsl(329deg 100% 36%) 33%, hsl(337deg 100% 43%) 44%, hsl(357deg 91% 59%) 56%, hsl(17deg 100% 59%) 67%, hsl(34deg 100% 53%) 78%, hsl(45deg 100% 50%) 89%, hsl(55deg 100% 50%) 100%)",
    use: false,
  },
  {
    name: "project-about",
    link: "",
    image: "Card.png",
    projectName: "신한 슈퍼 SQL 유지운영 2024",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient:
      "linear-gradient(45deg, hsl(240deg 100% 20%) 0%, hsl(289deg 100% 21%) 11%, hsl(315deg 100% 27%) 22%, hsl(329deg 100% 36%) 33%, hsl(337deg 100% 43%) 44%, hsl(357deg 91% 59%) 56%, hsl(17deg 100% 59%) 67%, hsl(34deg 100% 53%) 78%, hsl(45deg 100% 50%) 89%, hsl(55deg 100% 50%) 100%)",
    use: true,
  },
  {
    name: "shinhan",
    link: "/work/shinhan",
    image: "PC_Card_project03.png",
    projectName: "신한 슈퍼 SQL 유지운영 2024",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient:
      "linear-gradient(45deg, hsl(240deg 100% 20%) 0%, hsl(289deg 100% 21%) 11%, hsl(315deg 100% 27%) 22%, hsl(329deg 100% 36%) 33%, hsl(337deg 100% 43%) 44%, hsl(357deg 91% 59%) 56%, hsl(17deg 100% 59%) 67%, hsl(34deg 100% 53%) 78%, hsl(45deg 100% 50%) 89%, hsl(55deg 100% 50%) 100%)",
    use: true,
  },
  {
    name: "lgcns",
    link: "/work/lgcns",
    image: "PC_Card_project06.png",
    projectName: "신한 슈퍼 SQL 유지운영 2024",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient:
      "linear-gradient(45deg, hsl(240deg 100% 20%) 0%, hsl(289deg 100% 21%) 11%, hsl(315deg 100% 27%) 22%, hsl(329deg 100% 36%) 33%, hsl(337deg 100% 43%) 44%, hsl(357deg 91% 59%) 56%, hsl(17deg 100% 59%) 67%, hsl(34deg 100% 53%) 78%, hsl(45deg 100% 50%) 89%, hsl(55deg 100% 50%) 100%)",
    use: true,
  },
  {
    name: "project-about",
    link: "/work/project-about",
    image: "Card.png",
    projectName: "신한 슈퍼 SQL 유지운영 2024",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient:
      "linear-gradient(45deg, hsl(240deg 100% 20%) 0%, hsl(289deg 100% 21%) 11%, hsl(315deg 100% 27%) 22%, hsl(329deg 100% 36%) 33%, hsl(337deg 100% 43%) 44%, hsl(357deg 91% 59%) 56%, hsl(17deg 100% 59%) 67%, hsl(34deg 100% 53%) 78%, hsl(45deg 100% 50%) 89%, hsl(55deg 100% 50%) 100%)",
    use: true,
  },
  {
    name: "t4k",
    link: "https://gsgev.com/",
    image: "t4k.png",
    projectName: "신한 슈퍼 SQL 유지운영 2024",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient:
      "linear-gradient(45deg, hsl(240deg 100% 20%) 0%, hsl(289deg 100% 21%) 11%, hsl(315deg 100% 27%) 22%, hsl(329deg 100% 36%) 33%, hsl(337deg 100% 43%) 44%, hsl(357deg 91% 59%) 56%, hsl(17deg 100% 59%) 67%, hsl(34deg 100% 53%) 78%, hsl(45deg 100% 50%) 89%, hsl(55deg 100% 50%) 100%)",
    use: true,
  },
  {
    name: "kb",
    link: "/work/kb",
    image: "PC_Card_project26.png",
    projectName: "신한 슈퍼 SQL 유지운영 2024",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient:
      "linear-gradient(45deg, hsl(240deg 100% 20%) 0%, hsl(289deg 100% 21%) 11%, hsl(315deg 100% 27%) 22%, hsl(329deg 100% 36%) 33%, hsl(337deg 100% 43%) 44%, hsl(357deg 91% 59%) 56%, hsl(17deg 100% 59%) 67%, hsl(34deg 100% 53%) 78%, hsl(45deg 100% 50%) 89%, hsl(55deg 100% 50%) 100%)",
    use: true,
  },
  {
    name: "hug",
    link: "/work/hug",
    image: "PC_Card_project46.png",
    projectName: "신한 슈퍼 SQL 유지운영 2024",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient:
      "linear-gradient(45deg, hsl(240deg 100% 20%) 0%, hsl(289deg 100% 21%) 11%, hsl(315deg 100% 27%) 22%, hsl(329deg 100% 36%) 33%, hsl(337deg 100% 43%) 44%, hsl(357deg 91% 59%) 56%, hsl(17deg 100% 59%) 67%, hsl(34deg 100% 53%) 78%, hsl(45deg 100% 50%) 89%, hsl(55deg 100% 50%) 100%)",
    use: true,
  },
  {
    name: "temp",
    link: "/work/temp",
    image: "PC_Card_project57.png",
    projectName: "신한 슈퍼 SQL 유지운영 2024",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient:
      "linear-gradient(45deg, hsl(240deg 100% 20%) 0%, hsl(289deg 100% 21%) 11%, hsl(315deg 100% 27%) 22%, hsl(329deg 100% 36%) 33%, hsl(337deg 100% 43%) 44%, hsl(357deg 91% 59%) 56%, hsl(17deg 100% 59%) 67%, hsl(34deg 100% 53%) 78%, hsl(45deg 100% 50%) 89%, hsl(55deg 100% 50%) 100%)",
    use: false,
  },
  {
    name: "project-about",
    link: "",
    image: "Card.png",
    projectName: "신한 슈퍼 SQL 유지운영 2024",
    projectClient: "신한은행",
    projectType: "공공기관, 업무시스템, APP, 유지운영",
    projectYear: "2024",
    gradient:
      "linear-gradient(45deg, hsl(240deg 100% 20%) 0%, hsl(289deg 100% 21%) 11%, hsl(315deg 100% 27%) 22%, hsl(329deg 100% 36%) 33%, hsl(337deg 100% 43%) 44%, hsl(357deg 91% 59%) 56%, hsl(17deg 100% 59%) 67%, hsl(34deg 100% 53%) 78%, hsl(45deg 100% 50%) 89%, hsl(55deg 100% 50%) 100%)",
    use: true,
  },
];

export default { worksSettingList };
