// worksList: 작업물 리스트
const worksSettingList = [
  {
    name: "shinhan",
    link: "/works/shinhan",
    image: "PC_Card_project03.png",
    gradient: "type01",
    use: true,
  },
  {
    name: "lgcns",
    link: "/works/lgcns",
    image: "PC_Card_project06.png",
    gradient: "type02",
    use: true,
  },
  {
    name: "project-about",
    link: "/works/project-about",
    image: "Card.png",
    gradient: "type03",
    use: true,
  },
  {
    name: "t4k",
    link: "https://gsgev.com/",
    image: "t4k.png",
    gradient: "type04",
    use: true,
  },
  {
    name: "kb",
    link: "/works/kb",
    image: "PC_Card_project26.png",
    gradient: "type05",
    use: true,
  },
  {
    name: "hug",
    link: "/works/hug",
    image: "PC_Card_project46.png",
    gradient: "type01",
    use: true,
  },
  {
    name: "temp",
    link: "/works/temp",
    image: "PC_Card_project57.png",
    gradient: "type03",
    use: false,
  },
  {
    name: "project-about",
    link: "",
    image: "Card.png",
    gradient: "type02",
    use: true,
  },
  {
    name: "shinhan",
    link: "/works/shinhan",
    image: "PC_Card_project03.png",
    gradient: "type04",
    use: true,
  },
  {
    name: "lgcns",
    link: "/works/lgcns",
    image: "PC_Card_project06.png",
    gradient: "type01",
    use: true,
  },
  {
    name: "project-about",
    link: "/works/project-about",
    image: "Card.png",
    gradient: "type02",
    use: true,
  },
  {
    name: "t4k",
    link: "https://gsgev.com/",
    image: "t4k.png",
    gradient: "type03",
    use: true,
  },
  {
    name: "kb",
    link: "/works/kb",
    image: "PC_Card_project26.png",
    gradient: "type05",
    use: true,
  },
  {
    name: "hug",
    link: "/works/hug",
    image: "PC_Card_project46.png",
    gradient: "type01",
    use: true,
  },
  {
    name: "temp",
    link: "/works/temp",
    image: "PC_Card_project57.png",
    gradient: "type02",
    use: false,
  },
  {
    name: "project-about",
    link: "",
    image: "Card.png",
    gradient: "type01",
    use: true,
  },
  {
    name: "shinhan",
    link: "/works/shinhan",
    image: "PC_Card_project03.png",
    gradient: "type03",
    use: true,
  },
  {
    name: "lgcns",
    link: "/works/lgcns",
    image: "PC_Card_project06.png",
    gradient: "type04",
    use: true,
  },
  {
    name: "project-about",
    link: "/works/project-about",
    image: "Card.png",
    gradient: "type01",
    use: true,
  },
  {
    name: "t4k",
    link: "https://gsgev.com/",
    image: "t4k.png",
    gradient: "type02",
    use: true,
  },
  {
    name: "kb",
    link: "/works/kb",
    image: "PC_Card_project26.png",
    gradient: "type03",
    use: true,
  },
  {
    name: "hug",
    link: "/works/hug",
    image: "PC_Card_project46.png",
    gradient: "type04",
    use: true,
  },
  {
    name: "temp",
    link: "/works/temp",
    image: "PC_Card_project57.png",
    gradient: "type05",
    use: false,
  },
  {
    name: "project-about",
    link: "",
    image: "Card.png",
    gradient: "type02",
    use: true,
  },
];

export default { worksSettingList };
